<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'id' => 7,
                'name' => 'Earth Stone Matte',
                'slug' => 'earth-stone-matte',
                'price' => 5000,
                'size_id' => 3,
                'quantity' => 78,
                'texture' => 'matte',
                'color_family' => 'brown',
                'image' => '/uploads/media68e4ce35329f7.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of earth stones tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-ESM-4040-20251014-113',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 8,
                'name' => 'Rockie Berge Matte',
                'slug' => 'rockie-berge-matte',
                'price' => 7000,
                'size_id' => 5,
                'quantity' => 50,
                'texture' => 'matte',
                'color_family' => 'brown',
                'image' => '/uploads/media68e4cf63cb4e2.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 5,
                'brand_id' => 1,
                'short_description' => 'Best of rockie berge tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-RBM-4040-20251014-154',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 9,
                'name' => 'GVT Kala',
                'slug' => 'gvt-kala',
                'price' => 5000,
                'size_id' => 3,
                'quantity' => 78,
                'texture' => 'matte',
                'color_family' => 'brown',
                'image' => '/uploads/media68e4cf63cb00c.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of gvt kala tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-gvt-4040-20251014-193',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 10,
                'name' => 'Spider White Marble',
                'slug' => 'spider-white-marble',
                'price' => 50000,
                'size_id' => 1,
                'quantity' => 1000,
                'texture' => 'gloss',
                'color_family' => 'black',
                'image' => '/uploads/media68e4d0459f4f6.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 4,
                'brand_id' => 1,
                'short_description' => 'Best of Spider white marble',
                'long_description' => 'null',
                'sku' => 'AIKEZ-SWB-4040-20251014-005',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 11,
                'name' => 'GVT Ayla',
                'slug' => 'gvt-ayla',
                'price' => 4600,
                'size_id' => 2,
                'quantity' => 50,
                'texture' => 'satin',
                'color_family' => 'white',
                'image' => '/uploads/media68e4ce35329f7.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 5,
                'brand_id' => 4,
                'short_description' => 'Best of gvt ayla tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-GVT-4040-20251014-229',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes satin tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 12,
                'name' => 'Nova Quartz Matte',
                'slug' => 'nova-quartz-matte',
                'price' => 6000,
                'size_id' => 3,
                'quantity' => 80,
                'texture' => 'matte',
                'color_family' => 'gray',
                'image' => '/uploads/media68e4ced46296e.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 2,
                'brand_id' => 5,
                'short_description' => 'Best of nova quartz tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-NQM-4040-20251014-211',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 13,
                'name' => 'Classic Sky Tile',
                'slug' => 'earth-stone-matte',
                'price' => 10000,
                'size_id' => 5,
                'quantity' => 21,
                'texture' => 'gloss',
                'color_family' => 'silver',
                'image' => '/uploads/media68e4ac926ce4a.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 1,
                'brand_id' => 4,
                'short_description' => 'Best of classic sky tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-CST-4040-20251014-900',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 14,
                'name' => 'Blanco Matte',
                'slug' => 'blanco-matte',
                'price' => 14000,
                'size_id' => 3,
                'quantity' => 78,
                'texture' => 'matte',
                'color_family' => 'silver',
                'image' => '/uploads/media68e4ce35329f7.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 4,
                'brand_id' => 4,
                'short_description' => 'Best of blanco matte tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-BMT-4040-20251014-113',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 15,
                'name' => 'Classic Ivory Matte',
                'slug' => 'classic-ivory-matte',
                'price' => 5000,
                'size_id' => 4,
                'quantity' => 41,
                'texture' => 'matte',
                'color_family' => 'white',
                'image' => '/uploads/media68e4cf63cb2c8.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of classic ivory tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-CIT-4040-20251014-678',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 16,
                'name' => 'Rhino Black',
                'slug' => 'rhino-black',
                'price' => 7000,
                'size_id' => 4,
                'quantity' => 69,
                'texture' => 'gloss',
                'color_family' => 'black',
                'image' => '/uploads/media68e4d0459f4f6.jpga',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 5,
                'brand_id' => 3,
                'short_description' => 'Best of black rhino tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-BRT-4040-20251014-540',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 17,
                'name' => 'GVT Carpi',
                'slug' => 'gvt-carpi',
                'price' => 5000,
                'size_id' => 3,
                'quantity' => 78,
                'texture' => 'satin',
                'color_family' => 'grey',
                'image' => '/uploads/media68e4ce35329f7.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 1,
                'brand_id' => 3,
                'short_description' => 'Best of gvt carpi tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-GVC-4040-20251014-437',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 18,
                'name' => 'Stone Crops',
                'slug' => 'stone-crops',
                'price' => 6700,
                'size_id' => 5,
                'quantity' => 290,
                'texture' => 'shinny',
                'color_family' => 'gold',
                'image' => '/uploads/media68e4cf63cb00c.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 4,
                'brand_id' => 2,
                'short_description' => 'Best of stones crop tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-SCT-4040-20251014-671',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 19,
                'name' => 'Silverware Natural Granites',
                'slug' => 'silverware-natural-granite',
                'price' => 5000,
                'size_id' => 4,
                'quantity' => 670,
                'texture' => 'satin',
                'color_family' => 'grey',
                'image' => '/uploads/media68e4ce35329f7.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 1,
                'short_description' => 'Best of silverware natural granite',
                'long_description' => 'null',
                'sku' => 'AIKEZ-SNG-4040-20251014-349',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 20,
                'name' => 'Sandwave Natural Granite',
                'slug' => 'sandwave-natural-granite',
                'price' => 67000,
                'size_id' => 2,
                'quantity' => 98,
                'texture' => 'satin',
                'color_family' => 'black',
                'image' => '/uploads/media68e4ced461e6b.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of natural sandwave granite',
                'long_description' => 'null',
                'sku' => 'AIKEZ-ESM-4040-20251014-113',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 21,
                'name' => 'Anti Slip Sandwave Granite',
                'slug' => 'anti-slip-sandwave-granite',
                'price' => 55000,
                'size_id' => 1,
                'quantity' => 46,
                'texture' => 'gloss',
                'color_family' => 'brown',
                'image' => '/uploads/media68e4ce35329f7.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of anti slip granite',
                'long_description' => 'null',
                'sku' => 'AIKEZ-ASG-4040-20251014-261',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 22,
                'name' => 'Meta Africa Gray Natural Granite',
                'slug' => 'meta-africa-gray-natural-granite',
                'price' => 5000,
                'size_id' => 5,
                'quantity' => 290,
                'texture' => 'satin',
                'color_family' => 'gray',
                'image' => '/uploads/media68e4d0459f4f6.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of meta africa natural granite',
                'long_description' => 'null',
                'sku' => 'AIKEZ-MAG-4040-20251014-562',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 23,
                'name' => 'Meta Africa Marble',
                'slug' => 'earth-stone-matte',
                'price' => 42000,
                'size_id' => 3,
                'quantity' => 100,
                'texture' => 'gloss',
                'color_family' => 'black',
                'image' => '/uploads/media68e4cf63cad80.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 2,
                'brand_id' => 3,
                'short_description' => 'Best of meta africa marbles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-MAB-4040-20251014-556',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 24,
                'name' => 'Rhino Brown Matte',
                'slug' => 'rhino-brown-matte',
                'price' => 8000,
                'size_id' => 4,
                'quantity' => 54,
                'texture' => 'matte',
                'color_family' => 'brown',
                'image' => '/uploads/media68e4ced462c9c.jpeg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 5,
                'brand_id' => 1,
                'short_description' => 'Best of rhino brown matte',
                'long_description' => 'null',
                'sku' => 'AIKEZ-RBM-4040-20251014-549',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 25,
                'name' => 'GVT Laine',
                'slug' => 'earth-stone-matte',
                'price' => 7500,
                'size_id' => 1,
                'quantity' => 33,
                'texture' => 'matte',
                'color_family' => 'gold',
                'image' => '/uploads/media68e4ac926cce5.jpeg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 3,
                'brand_id' => 2,
                'short_description' => 'Best of gvt laine tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-GVL-4040-20251014-113',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ],
            [
                'id' => 26,
                'name' => 'Brown Parada Tile',
                'slug' => 'brown-parada-tile',
                'price' => 5000,
                'size_id' => 2,
                'quantity' => 46,
                'texture' => 'satin',
                'color_family' => 'gray',
                'image' => '/uploads/media68e4cf63cad80.jpg',
                'image2' => 'null',
                'image3' => 'null',
                'image4' => 'null',
                'category_id' => 4,
                'brand_id' => 1,
                'short_description' => 'Best of brown parada tiles',
                'long_description' => 'null',
                'sku' => 'AIKEZ-BPT-4040-20251014-250',
                'seo_title' => 'best tiles collections',
                'seo_description' => 'When it comes matte tiles, theses are the best you can ever get',
                'status' => 1
            ]
        ]);
    }
}
